title:               jmgao
url:                 https://jmgao.dev
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Josh Gao
  url:               jmgao.dev
  email:             me@jmgao.dev

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
